kind: Service
apiVersion: v1
metadata:
  name: csi-vast-snapshotter
  labels:
    app: csi-vast-snapshotter
spec:
  selector:
    app: csi-vast-snapshotter
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-vast-snapshotter
spec:
  serviceName: "csi-vast-snapshotter"
  replicas: 1
  selector:
    matchLabels:
      app: csi-vast-snapshotter
  template:
    metadata:
      labels:
        app: csi-vast-snapshotter
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-vastplugin
            topologyKey: kubernetes.io/hostname
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v1.2.0
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --connection-timeout=15s
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-vast
            type: DirectoryOrCreate
          name: socket-dir
