{{/* Vast CSI Node */}}

{{- $vast_config := .Files.Get "vast-config.yaml"  | fromYaml -}}
{{- $csi_images := get $vast_config "image" -}}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-vast-node
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
    {{- include "vastcsi.labels" . | nindent 4 }}
    app.kubernetes.io/csi-role: "node"
spec:
  selector:
    matchLabels:
      app: "csi-vast-node"
      {{- include "vastcsi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: csi-vast-node
        role: csi-vast
        {{- include "vastcsi.labels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
          {{- .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{- .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: csi-node-driver-registrar
          image: {{ printf "%s:%s" $csi_images.csiNodeDriverRegistrar.repository $csi_images.csiNodeDriverRegistrar.tag }}
          args: {{- include "vastcsi.commonArgs" . | nindent 12 }}
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          imagePullPolicy: {{ .Values.imagePullPolicy | default  "IfNotPresent" }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi.vastdata.com /registration/csi.vastdata.com-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.vastdata.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- if .Values.resources }}
          resources:
            {{- .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
        - name: csi-vast-plugin
          image: {{ printf "%s:%s" .Values.csiImage .Values.csiImageTag }}
          args:
            - "serve"
          imagePullPolicy: {{ .Values.imagePullPolicy | default  "IfNotPresent" }}
          env:
            {{- include "vastcsi.commonEnv" . | indent 12 }}
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          {{- if .Values.resources }}
          resources:
            {{- .Values.resources | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            {{- include "vastcsi.vmsAuthVolumeMount" . | indent 12 }}
      hostNetwork: true
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      serviceAccount: csi-vast-node-sa
      {{- if .Values.tolerations }}
      tolerations:
        {{- .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.vastdata.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        {{- include "vastcsi.vmsAuthVolume" . | indent 8 }}
