{{/* Credentials for comminication with Vast Cluster host */}}

{{- $checksum := cat .Values.username  .Values.password | sha256sum -}}
{{- $existing_sec := ( lookup "v1" "Secret" .Release.Namespace "csi-vast-mgmt" ) -}}

apiVersion: v1
kind: Secret
metadata:
  name: csi-vast-mgmt
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
  {{- include "vastcsi.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ $checksum  }}
type: Opaque
data:
  {{- if not $existing_sec }}
  username: {{ required "username is required" .Values.username | b64enc | quote }}
  password: {{ required "password is required" .Values.password | b64enc | quote }}
  {{- else }}
  {{- $existing_checksum := get $existing_sec.metadata.annotations "checksum/secret" -}}
  {{- if and .Values.username .Values.password ( ne $existing_checksum $checksum ) }}
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
  {{- else }}
  username: {{ $existing_sec.data.username }}
  password: {{ $existing_sec.data.password }}
  {{- end }}
  {{- end }}
