{{/* Optional ssl certificate for comminication with Vast Cluster host */}}

{{- $ssl_checksum := printf "%s" (include "vastcsi.sslChecksum" .) | trim -}}
{{- if ne $ssl_checksum ( quote "" )   }}
{{- if not ( contains "-----BEGIN CERTIFICATE-----" .Values.sslCert ) -}}
  {{- fail "Invalid sslCert. Use `helm install ... --set-file sslCert=< path to sslCert >` to provide valid certificate" -}}
{{- else if not .Values.verifySsl -}}
  {{- fail "When sslCert is provided `verifySsl` must be set to true." -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: csi-vast-vms-authority
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
  {{- include "vastcsi.labels" . | nindent 4 }}
  annotations:
    checksum/vast-vms-authority-secret: {{ $ssl_checksum  }}
type: Opaque
data:
  sslCert: |-
    {{ .Values.sslCert  | b64enc }}
{{- end -}}
