apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-vast-controller-sa
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
  {{- include "vastcsi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-vast-node-sa
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
  {{- include "vastcsi.labels" . | nindent 4 }}
