apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-vast-sc
provisioner: csi.vastdata.com
parameters:
  # All parameters are optional. If not provided default parameters from wizard setup are used.
  vip_pool_name: vippool-1
  root_export: /k8s
  mount_options: ''
  volume_name_fmt: csi:{namespace}:{name}:{id}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
